### ISSUE TITLE
Documentation on mas update 

### ISSUE THREAD

**Issue by mudspringhiker** [ibm-mas/installer#1002]
Docs on mas update [here](https://ibm-mas.github.io/cli/guides/update/) and [here](https://ibm-mas.github.io/cli/commands/update/) do not discuss what tasks are done aside from updating the operator catalog (such as update-mongodb, update-kafka, update-uds, etc).

**Comment by durera** [comment]
I'm going to move this function to the new python-based stack and tidy up the function docs while I'm at it ...
