### ISSUE TITLE
storageclass for db2 when using `mas install`

### ISSUE THREAD

**Issue by mudspringhiker** [ibm-mas/installer#1011]
Add the ability to specify a different storageclass for Db2 when using the `mas install` command. This is requested by a customer who hits a failure in the db2 installation using manage-premium. They want to keep manage-premium for MAS core and dependencies, but want to use ODF for db2.

**Comment by istrate** [comment]
@mudspringhiker We already have the functionality to do that. Just export these variables: https://github.com/ibm-mas/ansible-devops/blob/b382a3fdb2e4fc62fc086fe4ff4485e1b36c517e/ibm/mas_devops/roles/db2/README.md#role-variables---storage

**Comment by mudspringhiker** [comment]
Thank you. We can test if these variables get picked up by the `mas install` command.
