### ISSUE TITLE
maxdemo selection should be made part of mas installation and not just a part of SNO

### ISSUE THREAD

**Issue by svelagap** [ibm-mas/installer#105]
We need to make the Maximo Demo selection to populate the DB2 database with demodata as part of mas installation. Currently it exists as a customization in the codebase.

**Comment by aroute** [comment]
+1

If the demo data can be made available via the CICD pipeline for SNO hardware pattern, it should also be made available for a standard OCP cluster.

**Comment by durera** [comment]
I previously fixed this as yes it was silly that this was added, but only for single node openshift, originally ... https://github.com/ibm-mas/cli/blob/master/image/cli/mascli/functions/pipeline_config_applications#L195-L199

Now, anyone that selects to install Manage will be asked whether to install demo data or not
