### ISSUE TITLE
`mas configure-mirror` gives "unknown parameter" output

### ISSUE THREAD

**Issue by mudspringhiker** [ibm-mas/installer#1075]
- seen in CLI v10.0.1, also in 9.5.0
- customer reported

**Comment by durera** [comment]
We used to have a whole range of aliases for the mas functions; in a previous update we cut some of the aliases to make it less confusing (as different people would refer to the same functions by different names) .... configure-airgap used to also be able to be called as configure-mirror, and there are two places in the doc where the consolidation to configure-airgap was not made and it was still referred to as configure-mirror.
