### ISSUE TITLE
Bad character on MAS Cluster Issuer with Cloudflare

### ISSUE THREAD

**Issue by Quentin-Despeisse** [ibm-mas/installer#1103]
Hello,

While setting up a Cloudflare custom domain with the CLI, it looks like a $ is added to the MAS Cluster Issuer name.
This causes the Certificate not being generated as the issuer isn't found.

After recreating the Suite CR without the $, this works well.

![Capture d’écran 2024-07-08 à 16 31 41](https://github.com/ibm-mas/cli/assets/175030646/afdf77d0-1e70-47b4-a13c-82999978fed6)

**Comment by durera** [comment]
Thanks for raising this, the bug will be fixed in the next release shortly.
