### ISSUE TITLE
manage-backup-restore.sh fails when manual certificate management is enabled.

### ISSUE THREAD

**Issue by JedrekWie** [ibm-mas/installer#1120]
When manual certificate management is enabled then `image/cli/mascli/backup-restore/manage-backup-restore.sh` (image path `/mascli/backup-restore/manage-backup-restore.sh`) script fails with following error: `Error from server (NotFound): namespaces "-o" not found`
<img width="774" alt="manage-backup-error" src="https://github.com/user-attachments/assets/1e1948cf-0667-4dcd-b46a-4af1f7dc95cd">

The issue seems to be obvious and requires simple fix by adding `$MAS_MANAGE_NAMESPACE` as a third argument of the
`backupSingleResource` function call within `checkForManualCertMgmt` function definition.
<img width="855" alt="manage-backup-fix" src="https://github.com/user-attachments/assets/cfbd6286-d896-4861-b104-c1d3038713e4">

**Comment by durera** [comment]
Thanks for the PR, I'll get this merged in and included in the next release :+1:

**Comment by durera** [comment]
Fix available in https://github.com/ibm-mas/cli/releases/tag/10.3.0
