### ISSUE TITLE
Azure autodetected Storage classes are wrongly automatically asigned to RWO and RWX

### ISSUE THREAD

**Issue by guillemmayolramis1** [ibm-mas/installer#1163]
### MAS CLI version

b3a834c9841a

### CLI function used

install

### What happened?

Please correct the order provided for the SC when deploying in Azure. Its wrong.
https://github.com/ibm-mas/cli/blob/1c09170dbbb85fbb117559e522db2a627bcc7565/python/src/mas/cli/install/app.py#L472
![Captura de pantalla 2024-08-08 a las 15 04 06](https://github.com/user-attachments/assets/0a0fa31d-3288-4ea0-ab5a-3c5069100818)

Correct mapping is

ReadWriteOnce  managed-premium
ReadWriteMany  azurefiles-premium

### Relevant log output

```shell
# 3. Azure
        elif getStorageClass(self.dynamicClient, "managed-premium") is not None:
            print_formatted_text(HTML("<MediumSeaGreen>Storage provider auto-detected: Azure Managed</MediumSeaGreen>"))
            print_formatted_text(HTML("<LightSlateGrey>  - Storage class (ReadWriteOnce): azurefiles-premium</LightSlateGrey>"))
            print_formatted_text(HTML("<LightSlateGrey>  - Storage class (ReadWriteMany): managed-premium</LightSlateGrey>"))
            self.storageClassProvider = "azure"
            self.params["storage_class_rwo"] = "azurefiles-premium"
            self.params["storage_class_rwx"] = "managed-premium"
```

**Comment by durera** [comment]
Thanks for raising this & apologies for the delay in responding.  The fix for this will be in the next release of the CLI.
