### ISSUE TITLE
Maximo Manage Settings - Database not respected 

### ISSUE THREAD

**Issue by indor79** [ibm-mas/installer#1167]
### MAS CLI version

10.5.0

### CLI function used

install

### What happened?

When running the installer interactively we select the option to customise the database settings:

14.3) Maximo Manage Settings - Database
Customise the schema, tablespace, indexspace, and encryption settings used by Manage
Customize database settings? [y/n]y
Schema: dbo
Tablespace: PRIMARY
Indexspace: PRIMARY
Customize database encryption settings? [y/n] n

But the summary does not pick this up. And the installation in the cluster will try to use the default values:

Summary prints this:
  + Database Settings
    + Schema .............................. Default
    + Username ............................ dbo
    + Tablespace .......................... Default
    + Indexspace .......................... Default

We expect it to print something like this:

  + Database Settings
    + Schema .............................. dbo
    + Username ............................ dbo
    + Tablespace .......................... PRIMARY
    + Indexspace .......................... PRIMARY
    

It seems there is a missmatch around what variables that should be used?

Sometimes it's mas_app_settings_db2_tablespace

https://github.com/ibm-mas/cli/blob/6942b570d3f5f435317648a8496ec47fa39fd6ee/python/src/mas/cli/install/settings/manageSettings.py#L106

And sometimes it's mas_app_settings_tablespace

https://github.com/ibm-mas/cli/blob/6942b570d3f5f435317648a8496ec47fa39fd6ee/python/src/mas/cli/install/summarizer.py#L184

### Relevant log output

```shell
mas_app_settings_db2_indexspace: PRIMARY
mas_app_settings_db2_schema: dbo
mas_app_settings_db2_tablespace: PRIMARY
```

**Comment by MColeman0102** [comment]
Hey - any progress on this or a workaround?

**Comment by durera** [comment]
Thanks for reporting this & apologies for the delay in responding.  A fix for this will be in the next release of the CLI.
