### ISSUE TITLE
Installation fails on TASK [Check for required environment variables]

### ISSUE THREAD

**Issue by ederfalmeida** [ibm-mas/installer#1174]
### MAS CLI version

10.4.4

### CLI function used

install

### What happened?

At the beginning of the installation process, it requests the AWS Access Key ID. I copied it, and past from AWS. The system does not record it and the installation fails.

The workaround is to run the export AWS_ACCESS_KEY_ID=<product_key_from_aws> before issuing the mas provision-aws command.

The same happens with the AWS_SECREt_ACCESS_KEY.

### Relevant log output

```shell
fatal: [localhost]: FAILED! => changed=false 
  assertion: lookup('env', 'AWS_ACCESS_KEY_ID') != ""
  evaluated_to: false
  msg: One or more required environment variables are not defined
```

**Comment by durera** [comment]
> CLI function used
> install

Just want to confirm for whoever looking into this; this is related to the `provision-aws` command not the `install` command

**Comment by durera** [comment]
The root cause is the lack of exports for the variables that are defined during the CLI prompts, without this the variables defined in `provision_aws` are not available when the Ansible playbook is running.
