### ISSUE TITLE
save parameters entered during mas install interactive command

### ISSUE THREAD

**Issue by mattlrx** [ibm-mas/installer#1186]
### Feature and motivation

when running the mas install command in interative mode, you need to answer questions to provide parameters.
in the latest version of the cli the entered values are not kept, therefore if the installation failed and you need to run the install command again, you need to enter all the values again. 

in previous version of the cli the values were saved and subsequent attempts at installing mas and applications would reused the previously entered values which would save time.
there were also default values (Y/n or y/N) 
there was also at the end of the install the command to run the install in non-interactive mode

all of those are gone.

The request is to save the values entered during the interactive install, so it can be reused for subsequent attempts on the same cluster or other clusters.
it could also be used for docummenting the options that were chosen

### Usage example

where it is possible to use the non-interacive install command, considering the amounts of parameters to enter it is complex to build the right command.

going through the interactive install once and get a file with all the parameters, would speed up subsequent installs

use of a template could also be useful so the parameters could be filled in first

**Comment by durera** [comment]
This will be available in the next release:

![image](https://github.com/user-attachments/assets/b80bcc56-ccf2-4200-86a7-97f66202ef5f)
