### ISSUE TITLE
Manage advanced settings do not work on SNO

### ISSUE THREAD

**Issue by durera** [ibm-mas/installer#1192]
### MAS CLI version

10.7.3

### CLI function used

install

### What happened?

The primary pipeline params are as expected, indicating that we are not using a RWX storage class:

```
{"name":"storage_class_rwx","value":""}
{"name":"storage_class_rwo","value":"lvms-vg1"}
```

The additional param for a specific storage class for manage doclinks is not defined, and the access mode is wrong.  I'm not familiar with this area, but the problem is specifically regarding handling of Manage advanced settings

```
{"name":"mas_app_settings_doclinks_pvc_storage_class","value":""}
{"name":"mas_app_settings_doclinks_pvc_accessmode","value":"ReadWriteMany"}
```

Looking at all the Manage advanced settings, it looks like none are set up SNO friendly, so I would imagine that since these were added they have never worked for a SNO install.

```
mas_app_settings_aio_flag: 'false'
mas_app_settings_base_lang: CS
mas_app_settings_bim_pvc_accessmode: ReadWriteMany
mas_app_settings_bim_pvc_storage_class: ''
mas_app_settings_default_jms: 'true'
mas_app_settings_demodata: 'false'
mas_app_settings_doclinks_pvc_accessmode: ReadWriteMany
mas_app_settings_doclinks_pvc_storage_class: ''
mas_app_settings_jms_queue_pvc_accessmode: ReadWriteMany
mas_app_settings_jms_queue_pvc_storage_class: ''
mas_app_settings_persistent_volumes_flag: 'true'
mas_app_settings_secondary_langs: EN
mas_app_settings_server_bundles_size: snojms
mas_app_settings_server_timezone: GMT
```

I don't know the details about what each of these do and what the expectations are in terms of what they should be set to with/without SNO involved.  I'm guessing the fact mas_app_settings_persistent_volumes_flag=true means that the doclinks pvc params become active in the install, but the value for the class hasn't been initialized at all, I would guess that in the code it's hardwired to copy the RWX storage class to these values when mas_app_settings_persistent_volumes_flag is set to true, but needs to have an "if SNO copy RWO values".

### Relevant log output

```shell
See above
```

**Comment by MaximoMiller** [comment]
Is there a way to vote or show support of a bug so they see it is impacting more people and will get more quickly addressed?

**Comment by ederfalmeida** [comment]
I was about to report this issue. The MAS deployment hangs because these 3 pods can't be created.

![image](https://github.com/user-attachments/assets/0a06dc3a-6bb2-4996-9b12-82cba3eee4e0)
