### ISSUE TITLE
`mas must-gather` log trace shows errors for fetching previous logs

### ISSUE THREAD

**Issue by mudspringhiker** [ibm-mas/installer#1203]
### Feature and motivation

Not a major issue but it would be nice if the red message "Error fetching previous logs for container x in pod y" is suppressed when `mas must-gather` command is running.
![Screenshot 2024-08-23 at 9 55 13 AM](https://github.com/user-attachments/assets/dfeed93c-7689-4184-a4d4-21ed989e2161)

This would avoid unnecessary concerns from users.

### Usage example

I just think this would be a better experience for users.

**Comment by durera** [comment]
Agreed, there's no reason to report an error in this case, we have no way to tell whether this fails because there are no previous logs versus some genuine problem.  Fix will be in the next release of the CLI.
