### ISSUE TITLE
Weird naming in GitHub Releases

### ISSUE THREAD

**Issue by faangbait** [ibm-mas/installer#1240]
### MAS CLI version

latest

### CLI function used

other

### What happened?

Is it intentional that the URL for the linux binary is `https://github.com/ibm-mas/cli/releases/download/10.9.2/mas-cli-linux-amd64-`?

### Relevant log output

```shell
n/t
```

**Comment by durera** [comment]
I've been meaning to fix this for a while, thanks for the nudge
