### ISSUE TITLE
REGISTRY_PUBLIC_PORT should not be mandatory

### ISSUE THREAD

**Issue by indor79** [ibm-mas/installer#1319]
### Feature and motivation

It is not uncommon with a registry that do not have a port in the path. When REGISTRY_PUBLIC_PORT is required we can not use does registries

### Usage example

error: unable to push icr.io/cpopen/ibm-maximo-operator-catalog: failed to upload blob sha256:734a660836e9f0a771a4cb7853e2c61d33f52a09fb6697ec47e3cbce49157774: Post "https://quay.registry.foo.orgl:443/v2/cpopen/ibm-maximo-operator-catal
og/blobs/uploads/"

It should support https://quay.registry.foo.org/v2/cpopen/ibm-maximo-operator-catal
og/blobs/uploads/

**Comment by durera** [comment]
Agreed, we'll look at making port optional in the ansible role (and the cli wrapper).

**Comment by durera** [comment]
I forgot to link it to the PR, but this is covered as part of this PR and will be available in the next release: 
- https://github.com/ibm-mas/cli/pull/1407
