### ISSUE TITLE
mirroring fail - Usage Error: Unsupported option "--mirror-uds"

### ISSUE THREAD

**Issue by indor79** [ibm-mas/installer#1323]
### MAS CLI version

11.5.0

### CLI function used

mirror-images

### What happened?

```
# podman  run --security-opt label=disable -it --rm -v /ext/mas/to-filesystem:/mnt/core quay.io/ibmmas/cli:latest mas mirror-images -m to-filesystem -d /mnt/core  -H $REGISTRY_HOST -P $REGISTRY_PORT -u $REGISTRY_USERNAME
 --password $REGISTRY_PASSWORD  --ibm-entitlement $IBM_ENTITLEMENT_KEY -c v9-241003-amd64 -C 9.0.x --mirror-catalog --mirror-core --mirror-iot --mirror-manage --mirror-cfs --mirror-uds --mirror-sls --mirror-tsm --mirror-mongo --no-confirm -x mas
IBM Maximo Application Suite Air Gap Image Mirror (v11.5.0)
Powered by https://github.com/ibm-mas/ansible-devops/

Usage Error: Unsupported option "--mirror-uds"
```

Documentation states that --mirror-uds should work, also the mirror_images function https://github.com/ibm-mas/cli/blob/dd57afc13913f739fefdeb7737d4b62b64af1f8e/image/cli/mascli/functions/mirror_images#L57

But it is not defined later in the [content selection](https://github.com/ibm-mas/cli/blob/dd57afc13913f739fefdeb7737d4b62b64af1f8e/image/cli/mascli/functions/mirror_images#L232)  of the function casing mirroring to fail 

### Relevant log output

```shell
Usage Error: Unsupported option "--mirror-uds"
```

**Comment by durera** [comment]
`--mirror-uds` is no longer required ... we need to update the docs.

UDS was replaced by DRO in the MAS dependency stack earlier in the year, and the service itself was shutdown entirely in June IIRC; there is no longer any UDS content to mirror hence the flag is no longer supported.
