### ISSUE TITLE
Missing the DB2 installation in non-Interactive Install Command

### ISSUE THREAD

**Issue by JonahLuckett** [ibm-mas/installer#1348]
### MAS CLI version

11.4.0

### CLI function used

install

### What happened?

The MASCLI v10.9.2 and later generates a defective Non-Interactive Install Command, missing the DB2 installation. This issue was observed during a new MAS install in another cluster, causing the manage service to fail to install due to the absence of DB2.

Potential duplicate of https://github.com/ibm-mas/cli/issues/1280

```shell
Steps to reproduce:
a. Copy login command for a cluster / use oc login after instantiating a podman container of mas cli:latest
b. Run the 'mas install' command which the options chosen as given below under ##config
Expected behavior:
 * Generated non-interactive script contains db2 config information.
```

**Comment by durera** [comment]
Fixed in https://github.com/ibm-mas/cli/pull/1358
