### ISSUE TITLE
Add a warning to "Best-Effort QoS" option that it removes cpu/memory requests/limits

### ISSUE THREAD

**Issue by mudspringhiker** [ibm-mas/installer#1349]
Choosing the "Best Effort QoS" in configuring pod templates in the MAS CLI results into the Suite CR having no cpu/memory requests/limits for all pods in the MAS core namespace. This is not recommended, as it causes coreapi pods to consume too much memory (>5GB each for a total of at least 15GB). Please refer to skills case [TS017756933](https://ibmsf.lightning.force.com/lightning/r/500Ke000005ACaBIAW/view). 

The performance team recommends to put a caveat for users on that when choosing the Best Effort QoS, it may result in unbounded resource utilization.

**Comment by durera** [comment]
Removing cpu/memory requests and limits is what Best Effort QoS means.

- https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/
- https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-besteffort

This is an advanced topic, and expectation is that the admin knows what they are doing/knows what the QoS they have chosen means.

> The performance team recommends to put a caveat for users on that when choosing the Best Effort QoS, it may result in unbounded resource utilization.

We already provide a link to the documentation that explains what the QoS levels mean:

```
            self.printDescription([
                "The CLI supports two pod template profiles out of the box that allow you to reconfigure MAS for either a guaranteed or best effort QoS level",
                "For more information about the Kubernetes quality of service (QoS) levels, see https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/",
                "You may also choose to use your own customized pod template definitions"
            ])
```
