### ISSUE TITLE
Grafana - Default Storage class not found

### ISSUE THREAD

**Issue by Maximo-Mike** [ibm-mas/installer#1369]
### MAS CLI version

11.10.0

### CLI function used

install

### What happened?

Grafana fails with error that the default Storage Class was not found. RedHat OpenShift Single Node with Logical Volume Manager for a Storage Class.

### Relevant log output

```shell
STEP-GRAFANA

Export all env vars defined in /workspace/settings
Using /opt/app-root/src/ansible.cfg as config file
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'
running playbook inside collection ibm.mas_devops

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [ibm.mas_devops.ansible_version_check : Verify minimum Ansible version is 2.10.3] ***
ok: [localhost] => changed=false 
  msg: All assertions passed

TASK [ibm.mas_devops.grafana : Grafana: Debug properties] **********************
ok: [localhost] => 
  msg:
  - Grafana action ......................... install
  - Grafana major version................... 5
  - Grafana v4 namespace ................... grafana
  - Grafana v5 namespace ................... grafana5

TASK [ibm.mas_devops.grafana : include_tasks] **********************************
included: /opt/app-root/lib64/python3.9/site-packages/ansible_collections/ibm/mas_devops/roles/grafana/tasks/install/main.yml for localhost

TASK [ibm.mas_devops.grafana : install : Determine storage classes] ************
included: /opt/app-root/lib64/python3.9/site-packages/ansible_collections/ibm/mas_devops/roles/grafana/tasks/install/determine-storage-classes.yml for localhost

TASK [ibm.mas_devops.grafana : determine-storage-classes : Load default storage class information] ***
included: /opt/app-root/lib64/python3.9/site-packages/ansible_collections/ibm/mas_devops/common_tasks/default_storage_classes.yml for localhost

TASK [ibm.mas_devops.grafana : default-storage-classes : Lookup default storage classes] ***
/opt/app-root/lib64/python3.9/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.30.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
fatal: [localhost]: FAILED! => changed=false 
  message: Failed to find default storage classes
  provider: null
  providerName: null
  rwo: null
  rwx: null
  success: false

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by durera** [comment]
Looks like you're using Ansible directly rather than the CLI ... Do you have any of the default supported storage classes available?

https://ibm-mas.github.io/cli/commands/install/#select-storage-classes

These are the only ones that work without you explicitly setting the storage class, Logical Volume Manager is not one of the default storage classes recognized, so you will have to pass in that choice with the appropriate environment variable: 

https://ibm-mas.github.io/ansible-devops/roles/grafana/#grafana_instance_storage_class

**Comment by Maximo-Mike** [comment]
We are using the MASCLI and in the past this worked with no issues. I can see from the change log there was an update regarding storageclass. If we use the previous version of MASCLI 11.9.3 and had no issues.

We tried to pass the appropriate environment variable GRAFANA_INSTANCE_STORAGE_CLASS and it did not work. We also tried to run the ansible playbook directly by passing the environment variable and it failed. We had to go back to the previous versions.

We have done multiple installs implementations with this configuration and it is now no longer working with the latest releases.

From: David Parker ***@***.***>
Date: Tuesday, November 26, 2024 at 6:33 AM
To: ibm-mas/cli ***@***.***>
Cc: Michael Marsonet ***@***.***>, Author ***@***.***>
Subject: Re: [ibm-mas/cli] Grafana - Default Storage class not found (Issue #1369)
Looks like you're using Ansible directly rather than the CLI ... Do you have any of the default supported storage classes available? https://ibm-mas.github.io/cli/commands/install/#select-storage-clas
External ***@***.******@***.***>)
  Report This Email<https://protection.inkyphishfence.com/report?id=bmV0b3JnMTIzMzcxMDEvbW1hcnNvbmV0QG1ybS1lYW0uY29tL2Q4NDRkOTdmMGM1YzliYWE4ZGNlZmI4M2M0NjAwY2IzLzE3MzI2MjA4MTguMzk4NzQ0Mw==#key=e2910dc8e637fbd00c1e760fdfa396b2>  FAQ<https://www.godaddy.com/help/report-email-with-advanced-email-security-40813>  GoDaddy Advanced Email Security, Powered by INKY<https://www.inky.com/protection-by-inky>


Looks like you're using Ansible directly rather than the CLI ... Do you have any of the default supported storage classes available?

https://ibm-mas.github.io/cli/commands/install/#select-storage-classes<https://shared.outlook.inky.com/link?domain=ibm-mas.github.io&t=h.eJxNjk2SgyAQha-SYrbRBmEUs8pVmgaVGpCUTVap3D04NYvZvp_vvZd4HkncLmKr9cE3gOhyl5H7Ndbt6fpYgFIEKjnj7hnizhVTgi8OKVDtuJYD19BRQubA4noRPyduD81Y1aD1pKSC1j64NPGej9wFzH0jgrfG-HlaJH3T7BCtp7A4q8mMUpLToCY9jIO0yvZ6tpMx-hwIvwOlxiUS1lh2vv-9bdAz4M_AP-n9AXxRSdQ.MEUCIQDWToJX58TzNTGsqYI3T9uZVx8hRVCtOrsL9tbdjOZj1QIgPHvu2Fr-22UCly85HilRI_DBc-9orZfHI2EN0cT-kqw>

These are the only ones that work without you explicitly setting the storage class, Logical Volume Manager is not one of the default storage classes recognized, so you will have to pass in that choice with the appropriate environment variable:

https://ibm-mas.github.io/ansible-devops/roles/grafana/#grafana_instance_storage_class<https://shared.outlook.inky.com/link?domain=ibm-mas.github.io&t=h.eJxNjsFuwyAQRH8lotfagKExzil_Yi3L2kE1ELGklyj_XrvKobfR0-jNPMWjbuJyErfW7nyRMvrUJeB-je328H0sEjJHv1EX6KfcWdayEcu1wgIZ5Mc7zDFzg4w0cysVVppxA2bxeRLfhz7Tjlc9GDNqpWVKULns8Jpq6ghSjyXJ4KwN07go_MLJA7iAtHhn0J6VQm-kHs1wHpTTrjeTG601xwD9DZQWl4jQYsl8fb_fpUchHIV_6PULbplQdA.MEQCICZeihiNCojJVK6N2wDuFsKSgC_5f0LFrYOMu3tsvwRvAiBSe4eLP9nzPyrVa1h_8ntH9_gIH570nTHxHz8wx_OVXw>
