### ISSUE TITLE
When installing predict using ibmcli 11.10.1 ,  stuck in cp4d

### ISSUE THREAD

**Issue by rhongau** [ibm-mas/installer#1380]
### MAS CLI version

11.10.1

### CLI function used

install

### What happened?

trying to Install mas/iot/monitor/manage/predict using cli ,  stuck in cp4d  
[cp4d.log](https://github.com/user-attachments/files/17928156/cp4d.log)

### Relevant log output

```shell
log attached
```

**Comment by rhongau** [comment]
export IBM_ENTITLEMENT_KEY=x
mas install --mas-catalog-version v9-241107-amd64 --ibm-entitlement-key $IBM_ENTITLEMENT_KEY \
  --mas-channel 9.0.x --mas-instance-id masdemo --mas-workspace-id masapdemo --mas-workspace-name "masapdemo" \
  --disable-walkme \
  --storage-class-rwo "ocs-storagecluster-ceph-rbd" --storage-class-rwx "ocs-storagecluster-cephfs" \
  --storage-pipeline "ocs-storagecluster-cephfs" --storage-accessmode "ReadWriteMany" \
  --license-file "/opt/app-root/src/masconfig/entitlement.lic" \
  --uds-email "r@mro.com" --uds-firstname "r" --uds-lastname "h" \
  --dro-namespace "redhat-marketplace" \
  --mongodb-namespace "mongoce" \
  --iot-channel "9.0.x" \
  --monitor-channel "9.0.x" \
  --manage-channel "9.0.x" \
  --predict-channel "9.0.x" \
  --manage-jdbc "workspace-application" \
  --manage-components "base=latest,health=latest" \
  --manage-server-bundle-size "dev" \
  --cp4d-version "4.8.0" \
  --db2-system \
  --db2-manage \
  --db2-channel "v110509.0" \
  --db2-namespace "db2u" \
  --db2-type "db2wh" \
  --db2-cpu-requests "4000m" \
  --db2-cpu-limits "6000m" \
  --db2-memory-requests "8Gi" \
  --db2-memory-limits "12Gi" \
  --db2-backup-storage "100Gi" \
  --db2-data-storage "100Gi" \
  --db2-logs-storage "100Gi" \
  --db2-meta-storage "20Gi" \
  --db2-temp-storage "100Gi" \
  --kafka-provider "strimzi" \
  --kafka-namespace "strimzi" \
  --kafka-version "3.7.0" \
  --accept-license --no-confirm

**Comment by rhongau** [comment]
if running with same setting using ibmcli version 11.9.0,  no cpd4 error. 
Please check

**Comment by IanBoden** [comment]
To understand what zen is waiting on we are going to need a mustgather from the cluster when zen is stuck.

**Comment by IanBoden** [comment]
This is a regression introduced in 11.9.2 when installing CP4D 4.8.0
