### ISSUE TITLE
mas install failing 

### ISSUE THREAD

**Issue by neilpatt** [ibm-mas/installer#151]
I am using the cli version 3.10.5 in an air gapped configuration. when trying to run mas install I get an error in the Ibm-common-servces pipeline

TASK [ibm.mas_devops.ibm_catalogs : Load CASE bundle versions for the offline catalog] ***
Thursday 26 January 2023  11:59:24 +0000 (0:00:00.053)       0:00:02.243 ****** 
fatal: [localhost]: FAILED! => {"ansible_facts": {}, "ansible_included_var_files": [], "changed": false, "message": "Could not find or access '/opt/app-root/lib64/python3.9/site-packages/ansible_collections/ibm/mas_devops/roles/ibm_catalogs/../../common_vars/casebundles/v8-20230111-amd64.yml' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}

looking in the directory above I do not see the file mentioned  I do see the following files

[ibmmas/cli:3.10.5]~$ ls -al /opt/app-root/lib64/python3.9/site-packages/ansible_collections/ibm/mas_devops/roles/ibm_catalogs/../../common_vars/casebundles/
total 32
drwxrwxr-x 1 default root  216 Jan 19 17:21 .
drwxrwxr-x 1 default root  135 Jan 19 17:21 ..
-rw-rw-r-- 1 default root 1716 Jan 19 17:21 v8-220717-amd64.yml
-rw-rw-r-- 1 default root 1716 Jan 19 17:21 v8-220717.yml
-rw-rw-r-- 1 default root 1716 Jan 19 17:21 v8-220805-amd64.yml
-rw-rw-r-- 1 default root 2015 Jan 19 17:21 v8-220927-amd64.yml
-rw-rw-r-- 1 default root 2369 Jan 19 17:21 v8-221025-amd64.yml
-rw-rw-r-- 1 default root 2533 Jan 19 17:21 v8-221129-amd64.yml
-rw-rw-r-- 1 default root 2533 Jan 19 17:21 v8-221228-amd64.yml
-rw-rw-r-- 1 default root 2533 Jan 19 17:21 v8-230111-amd64.yml

**Comment by durera** [comment]
It's looking for `v8-20230111-amd64.yml` .. implying that `MAS_CATALOG_VERSION` was set to `v8-20230111-amd64` instead of `v8-230111-amd64` ... did you hit this passing in your own `MAS_CATALOG_VERSION` or using one of the playbooks/MAS CLI?

**Comment by neilpatt** [comment]
I was using the cli to select the MAS Catalog Version

**Comment by durera** [comment]
Thanks, this will be fixed in the next release (in a few minutes)
