### ISSUE TITLE
Pod error when installing MAS 8.8 on an existing OCP in Azure

### ISSUE THREAD

**Issue by zxue** [ibm-mas/installer#184]
Failed to pull image "us.icr.io/techzone/kubeturbo:8.8.0": rpc error: code = Unknown desc = unable to retrieve auth token: invalid username/password: unauthorized: The login credentials are not valid, or your IBM Cloud account is not active.

**Comment by zxue** [comment]
The issue may be specific to the testing environment, not related to the CLI command.

**Comment by andrercm** [comment]
@zxue thanks for your feedback.
Have you resolved your problem?
