### ISSUE TITLE
Mas Mirror images Breaking 

### ISSUE THREAD

**Issue by neilpatt** [ibm-mas/installer#190]
Trying to mirror the images for MAS Core and Mas Manage 8.9.1 and 8.9.2 - mirroring fails with

fatal: [localhost]: FAILED! => {"changed": true, "cmd": "oc ibm-pak get ibm-mas --version 8.9.1", "delta": "0:00:12.815272", "end": "2023-02-24 07:06:07.015168", "msg": "non-zero return code", "rc": 1, "start": "2023-02-24 07:05:54.199896", "stderr": "Error: Unable to validate a signature object for the CASE ibm-mas-assist->=8.1.0 <9.0.0", "stderr_lines": ["Error: Unable to validate a signature object for the CASE ibm-mas-assist->=8.1.0 <9.0.0"], "stdout": "Downloading and extracting the CASE ...\n- Success\nRetrieving CASE version ...\n- Success\nValidating the CASE ...\nValidating the signature for the ibm-mas CASE...\n- Success\nCreating inventory ...\n- Success\nFinding inventory items\n- Success\nResolving inventory items ...\nParsing inventory items\nValidating the signature for the ibm-mas-monitor CASE...\nValidating the signature for the ibm-mas-iot CASE...\nValidating the signature for the ibm-mas-manage CASE...\nValidating the signature for the ibm-mas-predict CASE...\nValidating the signature for the ibm-mas-visualinspection CASE...\nValidating the signature for the ibm-mas-assist CASE...", "stdout_lines": ["Downloading and extracting the CASE ...", "- Success", "Retrieving CASE version ...", "- Success", "Validating the CASE ...", "Validating the signature for the ibm-mas CASE...", "- Success", "Creating inventory ...", "- Success", "Finding inventory items", "- Success", "Resolving inventory items ...", "Parsing inventory items", "Validating the signature for the ibm-mas-monitor CASE...", "Validating the signature for the ibm-mas-iot CASE...", "Validating the signature for the ibm-mas-manage CASE...", "Validating the signature for the ibm-mas-predict CASE...", "Validating the signature for the ibm-mas-visualinspection CASE...", "Validating the signature for the ibm-mas-assist CASE..."]}

this seems to be a problem with the ibm-pak code - trying to get the pak using 

oc ibm-pak get ibm-mas --version 8.9.1 -v 2

returns the following error

Error: Unable to validate a signature object for the CASE ibm-mas-assist->=8.1.0 <9.0.0

**Comment by durera** [comment]
This will be "fixed" in the next release, I say "fixed" because the underlying issue isn't in the automation code, but rather an issue with a corrupt CASE bundle.  We will have to seperately address that, but some optimization of the mirroring process (https://github.com/ibm-mas/ansible-devops/pull/693) will ensure that the corrupt ibm-mas-assist dependency isn't a problem when mirroring the core content.
