### ISSUE TITLE
Update catalog support for MAS 8.10 release

### ISSUE THREAD

**Issue by terenceq** [ibm-mas/installer#211]
## Publish a new curated catalog containing updates from the MAS 8.10 release cycle.

March patch content will be released on or around March 28th and will be available in the official IBM Operator Catalog. This issue will track the updates and release of the IBM Maximo Operator Catalog.

Curated content from the IBM Operator Catalog was refreshed on February 28th.

The release tag for the catalog will be 230328

**Comment by andrercm** [comment]
@terenceq I believe we can close this for now?

**Comment by whitfiea** [comment]
[v3.18.0](https://github.com/ibm-mas/cli/releases/tag/3.18.0) delivered this
