### ISSUE TITLE
Improve build system support for master pre-release build

### ISSUE THREAD

**Issue by durera** [ibm-mas/installer#222]
Today, we have fairly simple logic that says:
- if there is a tgz in the ansible-install directory use that
- otherwise, use the latest release from galaxy

We want the logic to be like this instead:
- if there is a tgz in the ansible-install directory use that
- otherwise, if we are building a branch (rather than a tag) use the latest master pre-release of ibm.mas_devops
- otherwise, use the latest release from galaxy

To achieve this, we will want to publish the pre-release and release builds of ibm.mas_devops to Artifactory using exactly the same logic we do with the tekton definitions in this repository.  We will then be able to have logic in the build that basically works like this:

if this is a branch build and there isn't a tgz in the ansible-install directory
- download the latest master pre-release tgz from artifactory and save it to the normal location

Should be fairly simple, will require updates in ansible-devops first so that the collection is published to artifactory.

**Comment by durera** [comment]
@andrercm , this is already done, right?  There wasn't anything else you still had to do for this?

**Comment by andrercm** [comment]
@durera yes, this is done, I'm working on the last piece of the build system improvements now which is the piece that will trigger cli rebuild when ansible-devops master/release is built. I'll close this one here.
