### ISSUE TITLE
Enhanced must-gather for Manage

### ISSUE THREAD

**Issue by durera** [ibm-mas/installer#280]
We need to implement https://github.com/ibm-mas/cli/blob/master/image/cli/mascli/must-gather/mg-collect-mas-manage to perform application-specific collection, see https://github.com/ibm-mas/cli/blob/master/image/cli/mascli/must-gather/mg-collect-mas-core for an example.

- Collect useful data from relavent databases
- Collect operator reconcile logs
- Collect useful files from mounted persistent volumes

**Comment by alicenahas** [comment]
This Git issue is related to Jira Epic [MASISMIG-43739](https://jsw.ibm.com/browse/MASISMIG-43739).

The Epic was breakdown in smaller stories:

- [MASISMIG-43667](https://jsw.ibm.com/browse/MASISMIG-43667) - [Research] - Must Gather for Manage
- [MASISMIG-44008](https://jsw.ibm.com/browse/MASISMIG-44008) - [Size / Planning] - Define stories needed to extend Must Gather for Manage
- [MASISMIG-44284](https://jsw.ibm.com/browse/MASISMIG-44284) - [Coding] - Adding Resources for Manage
    -  PR: https://github.com/ibm-mas/cli/pull/408
- [MASISMIG-44675](https://jsw.ibm.com/browse/MASISMIG-44675) - [Summary] - Add Manage CRs information on Summary file
    -  PR: https://github.com/ibm-mas/cli/pull/443
- [MASISMIG-44676](https://jsw.ibm.com/browse/MASISMIG-44676) - [Reconciled logs] - Investigate and Add, if needed, Manage Reconciled Logs
    -  PR: https://github.com/ibm-mas/cli/pull/453
- [MASISMIG-44677](https://jsw.ibm.com/browse/MASISMIG-44677) - [POD INFO] - It would be good if each pod could have its own folder
    -  PR: https://github.com/ibm-mas/cli/pull/511
- [MASISMIG-45812](https://jsw.ibm.com/browse/MASISMIG-45812) - [POD INFO] - It would be good if each pod could have its own folder - PART 2
    -  PR: https://github.com/ibm-mas/cli/pull/535
