### ISSUE TITLE
Enhanced must-gather for SLS

### ISSUE THREAD

**Issue by durera** [ibm-mas/installer#286]
We need to detect instances of SLS in the cluster, and perform must-gather similar to how we do for the Suite itself.

**Comment by rawa-resul** [comment]
@durera any examples on how to do that?

**Comment by stonepd** [comment]
@rawa-resul - I'll do this one, should be simple having done https://github.com/ibm-mas/cli/issues/279

Do you have any specific files that would be useful to gather?

**Comment by rawa-resul** [comment]
@stonepd hmm no specific file in mind but I would say the usual resources

- CRs
- Pod logs
- ConfigMaps
- Routes & Services
- (I don't thin we are allowed Secrets?)

**Comment by stonepd** [comment]
@rawa - the mustgather currently contains secrets

**Comment by stonepd** [comment]
@rawa-resul - for CRs in the SLS namespace I was thinking LicenseService and LicenseClient, any others?

**Comment by rawa-resul** [comment]
@stonepd ah nice - would be great to include their entitlement/license file secret. `ibm-sls-<instanceId>-entitlement`

**Comment by rawa-resul** [comment]
> @rawa-resul - for CRs in the SLS namespace I was thinking LicenseService and LicenseClient, any others?

that's correct. I would assume one LicenseService CR and mostly just one LicenseClient CR but can be more if it's a shared SLS env.
