### ISSUE TITLE
Add option to select the name of the ingress secret

### ISSUE THREAD

**Issue by gojeaqui** [ibm-mas/installer#302]
By default `mas install` assumes that the Openshift cluster has the default ingress certificates with a secret name of: `router-certs-default`.

But we have replaced the default ingress certificates following this documentation:
https://docs.openshift.com/container-platform/4.10/security/certificates/replacing-default-ingress-certificate.html

We would need to be able to set the name of the secret, since the documentation allows you to set any name you want.

Thanks!

**Comment by andrercm** [comment]
Fixed this problem in the following PR: https://github.com/ibm-mas/cli/pull/568

Now it's possible to customize `ocp_ingress_tls_secret_name` variable by two ways via the cli:

1. If running `mas install` using interactive mode (user is prompted with questions), in the `Advanced Settings` step, you can opt to `Configure Advanced Settings` and you can now type the cluster ingress cert you want to use in case you have altered that config in the cluster when you are prompted by `Default cluster ingress certificate secret` question.
2. Alternatively, while using the non-interactive mode (silent install) you can use the argument `--ocp-ingress-tls-secret-name $MY_INGRESS_SECRET` with the `mas install` command

Once the pipeline is triggered, the `ocp-verify` task will now lookup for the Cluster ingress cert secret based upon the secret name specified, as example:

```
export IBM_ENTITLEMENT_KEY=xxx
mas install --mas-catalog-version v8-amd64 --accept-license \
  --license-file /tmp/entitlement.lic \
  --uds-email 'mas@test.com' --uds-firstname 'mas' --uds-lastname 'mas' \
  --storage-rwo 'ibmc-block-silver' --storage-rwx 'ibmc-file-silver' --storage-pipeline 'ibmc-file-silver' --storage-accessmode 'ReadWriteMany' \
  --mas-instance-id 'test' --mas-workspace-id 'main' --mas-workspace-name 'main' \
  --mas-channel '8.10.x' --additional-configs /tmp --non-prod --ocp-ingress-tls-secret-name router-metrics-certs-default
```

<img width="790" alt="image" src="https://github.com/ibm-mas/cli/assets/31037381/38b2a23d-c93c-4f68-bedc-8181843b0692">
