### ISSUE TITLE
Add support to enable OpenTelemetry in monitoring stack

### ISSUE THREAD

**Issue by durera** [ibm-mas/installer#325]
`CLUSTER_MONITORING_INCLUDE_OPENTELEMETRY` environment variable must be able to be passed into the cluster_monitoring role (boolean) ... this defaults to False inside the role.  User only needs to set this if they want to use OpenTelemetry, and right now we don't acctively make use of this operator anyway.

**Comment by terenceq** [comment]
@durera has this issue been addressed with the refactoring of the Grafana Tekton Task?

**Comment by durera** [comment]
It hasn't, but I'm going to close this as not seeing any push for OT, it seems to have fallen away in terms of priority.
