### ISSUE TITLE
mirroring OpenShift release and operator catalog does not do anything

### ISSUE THREAD

**Issue by witekwww** [ibm-mas/installer#364]
When using interactive mirroring and selecting only to mirror Red Hat OpenShift Container Platform Release and Red Hat OpenShift Container Platform Operator Catalog mirroring process does not start at all.
See attached screenshot:
![image](https://github.com/ibm-mas/cli/assets/118370754/de86f2d0-2142-409b-81c9-f83d7bb4a58f)

**Comment by durera** [comment]
A few releases ago the redhat mirroring was improved and expanded to support mirroring a partial subset of the redhat operator catalog required by MAS, as part of that it was given it's own standalone command: https://ibm-mas.github.io/cli/commands/mirror-redhat-images/

One of the changes in v6 was to fix some lingering prompts in `mirror-images` that related to the old version of redhat image mirroring that was embedded in that command, which is what you are seeing here.

To mirror redhat content for MAS use e.g. 

```
docker run -ti --rm -v /home/me/mas:/mnt/local --pull Always quay.io/ibmmas/cli mas mirror-redhat-images \
  --mode to-filesystem \
  --dir /mnt/local/mirror \
  --pull-secret /mnt/local/pull-secret.json
  --mirror-platform \
  --mirror-operators \
  --release 4.12
```
