### ISSUE TITLE
Generating MAS Workspace Name Fails in Interactive Mode

### ISSUE THREAD

**Issue by kathleenhosang** [ibm-mas/installer#410]
When running mas install in interactive mode, workspace names that should be accepted are not accepted. See two examples below:
![Screenshot 2023-08-11 at 4 20 22 PM](https://github.com/ibm-mas/cli/assets/40863347/4084937b-86cb-45c6-bc66-e1894437b453)

![Screenshot 2023-08-11 at 4 20 14 PM](https://github.com/ibm-mas/cli/assets/40863347/c016df52-3e14-42e4-a24b-9f095c5e3685)

I locally removed the if statement below to get around this, but can we please check the syntax.

![Screenshot 2023-08-11 at 4 17 35 PM](https://github.com/ibm-mas/cli/assets/40863347/a38c56cc-b19f-43e5-b419-6c68cb6fdd34)

**Comment by durera** [comment]
This is/should be fixed in the release from earlier today if you check 6.3.2 👍

**Comment by durera** [comment]
https://github.com/ibm-mas/cli/pull/409

**Comment by kathleenhosang** [comment]
Awesome! Yup, I was using 3.6.1. No issues on Fyre with 3.6.2 👍

Katie Ho Sang
IBM Software, Expert Labs
1 646 612 0932 Mobile
she/her

________________________________
From: David Parker ***@***.***>
Sent: Friday, August 11, 2023 4:33 PM
To: ibm-mas/cli ***@***.***>
Cc: Kathleen Ho Sang ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [ibm-mas/cli] Generating MAS Workspace Name Fails in Interactive Mode (Issue #410)

#409 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread. Message ID: <ibm-mas/cli/issues/410/1675373017@ github. com> ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!2i-q6PXc4ROy2c_QU6KupplBpsftje31_KFhLDbGhH3IuXRkForjMa_1GMRGzRlvIcDomwnTceL69wnSjrx_GRD9Z2SS8X9d$>
Report Suspicious

ZjQcmQRYFpfptBannerEnd

#409<https://github.com/ibm-mas/cli/pull/409>
