### ISSUE TITLE
app-install-visualinspection fails with mas_app_settings_visualinspection_storage_class must be defined

### ISSUE THREAD

**Issue by aeisma** [ibm-mas/installer#422]
ibmmas/cli:6.4.2 app-install-visualinspection fails with:

```
TASK [ibm.mas_devops.suite_app_install : Assert that storage class has been defined] ***
Wednesday 16 August 2023  11:54:23 +0000 (0:00:00.041)       0:00:01.706 ****** 
fatal: [localhost]: FAILED! => {
    "assertion": "mas_app_settings_visualinspection_storage_class is defined and mas_app_settings_visualinspection_storage_class != \"\"",
    "changed": false,
    "evaluated_to": false,
    "msg": "mas_app_settings_visualinspection_storage_class must be defined"
}
```

This is when custom storage classes are defined as the cli does not select to correct storage classes by default.
We have selected the following, and the Core install completes successfully.

ReadWriteOnce (RWO) storage class > managed-premium
ReadWriteMany (RWX) storage class > azure-file

**Comment by andrercm** [comment]
It's missing defining the rwx storage class for the `mas_app_settings_visualinspection_storage_class` property.
This is fixed in the linked pull request above.
