### ISSUE TITLE
missing dependencies used by MAS Core and Manage backup and restore

### ISSUE THREAD

**Issue by terenceq** [ibm-mas/installer#431]
## MAS Core and Manage backup and restore dependencies

The MAS Core and Manage backup procedures document to use the following tools:

- Mongo Shell
- mongodump
- mongorestore
- yq

The CLI container should control the install and version of these tools so compatibility can be maintained.

**Comment by durera** [comment]
Closing issue.  This was delivered on Aug 21st in #432
