### ISSUE TITLE
Missing cp4d_primary_storage_class in cpd taskdef

### ISSUE THREAD

**Issue by andrercm** [ibm-mas/installer#457]
This is to fix reported issue: https://github.ibm.com/wiotp/tracker/issues/13355

It seems we're are missing to set the cpd_primary_storage_class to a the storage class defined in the MAS cli install:
https://github.com/ibm-mas/cli/blob/master/tekton/src/pipelines/taskdefs/cp4d/cp4d-platform.yml.j2

whereas in kafka we do that:
https://github.com/ibm-mas/cli/blob/master/tekton/src/pipelines/taskdefs/dependencies/kafka.yml.j2#L19

So the issue here is that cpd will only be installed if a default storage is found, but in the case users defined a custom storage class in MAS cli, this info is not passed to the pipeline.

**Comment by mattlrx** [comment]
@andrercm the same applies to the other variable **cpd\_metadata\_storage\_class**

**Comment by andrercm** [comment]
yep im fixing both @mattlrx

**Comment by andrercm** [comment]
ok so made the changes to allow cli to pass in custom storage classes if defined by user... now cp4d tasks is using it:

CLI output:
<img width="450" alt="image" src="https://github.com/ibm-mas/cli/assets/31037381/b934c7ef-6714-4c73-8ed2-9a6252c475af">

Pipeline output:
<img width="1093" alt="image" src="https://github.com/ibm-mas/cli/assets/31037381/1391fb79-eac9-4978-99e6-867c017f2c5f">

It will be available with this pull request:
https://github.com/ibm-mas/cli/pull/459
