### ISSUE TITLE
Kafka Version cannot be set via pipeline

### ISSUE THREAD

**Issue by durera** [ibm-mas/installer#552]
We can't assume customers are using the latest Red Hat operator catalogs, in which case they may not have a version of Strimzi/AMQ Streams that can support the latest versions of Kafka and we need to allow them to set the version accordingly (using existing `KAFKA_VERSION`).

**Comment by ekambaraml** [comment]
Thank you David for opening this case. Currently Dubai Municipality customer is in this situation.

**Comment by andrercm** [comment]
i'll work on this one

**Comment by andrercm** [comment]
@durera i see you have a change for that already in an upcoming branch, i had done very similar changes to another branch i'm actively working so i'll revert my changes.

**Comment by andrercm** [comment]
Noticed you're PR does not have `--kafka-version` in `install` function, if you want I can have it added with my PR (it's already implemented in my branch)

**Comment by durera** [comment]
Haha, yeah I checked earlier this afternoon and this was still unassigned so I had a run at it because we really need this available tomorrow to unblock an important install.
