### ISSUE TITLE
Documentation update 

### ISSUE THREAD

**Issue by matteodamico** [ibm-mas/installer#580]
In the [IBM Maximo Operator Catalog v8 (231004)documentation ](https://ibm-mas.github.io/cli/catalogs/v8-231004-amd64/) is mentioned that supports only MAS 8.9 and MAS 8.10.
is the MAS 8.11 supported? should the page be updated?

**Comment by durera** [comment]
I fixed this (and various other mistakes in the docs) in https://github.com/ibm-mas/cli/pull/649
