### ISSUE TITLE
Update command should show installed MAS instances

### ISSUE THREAD

**Issue by durera** [ibm-mas/installer#632]
Although user doesn't need to select a MAS instance because update affects the whole cluster, we should show the same list of MAS instances to the user (after the review catalog output)  so that the user can clearly see what instances will be affected.

Current output: update
![image](https://github.com/ibm-mas/cli/assets/4400618/1cd47ea8-7f61-4b16-b925-8ebb0c812341)

Current output: upgrade
![image](https://github.com/ibm-mas/cli/assets/4400618/78593b52-2c6c-47da-8cd2-451b41824628)

**Comment by terenceq** [comment]
Closing as the PR:

https://github.com/ibm-mas/cli/pull/823

should address the issue.
