### ISSUE TITLE
Add option to include demo data when installing Manage

### ISSUE THREAD

**Issue by pmvester** [ibm-mas/installer#70]
When installing MAS using the ibmmas/cli container image by executing the “mas provision-xxxx” and “mas install” commands there is no way to force the installation of demo data. As this a very attractive and smooth way to install MAS I and my business partners would really appreciate if there was a way to include demo data (as opposed to running a number of Ansible playbooks in sequence).

Mikael Vester, IBM Technical Sales, Sustainability Software

**Comment by durera** [comment]
This option is now available in the CLI, but the issue wasn't updated ... if user selects to install Manage they will be prompted whether or not to install demo data.

https://github.com/ibm-mas/cli/blob/d57896d9a872b73f98476253b0a3b4f2db7fe87c/image/cli/mascli/functions/pipeline_config_applications#L195-L199

https://github.com/ibm-mas/cli/commit/c35378ceace8e929356d749078a11254cc19a364
