### ISSUE TITLE
Error at database configuration for Maximo IoT

### ISSUE THREAD

**Issue by JesperAP** [ibm-mas/installer#733]
When using the mas install cmd and selecting "Yes" at the question "SSL Enabled [y/n]: Y" I get a Python error message. See screenshot below.

(i have removed the connection string, username and password, those are not blank when executing the install CMD)

![image](https://github.com/ibm-mas/cli/assets/149156811/8c8b3fe6-a69e-453c-a82a-388789a647a8)

**Comment by whitfiea** [comment]
@JesperAP Are you still seeing this issue? As there is no jdbcfg config provided and the SSL enabled is true, it is looking for the location of the file containing the SSL Certificate(s) to trust. It should have prompted you for that location.

**Comment by istrate** [comment]
closing and addressed
