### ISSUE TITLE
Support for installing OCP 4.12 (or higher) on AWS

### ISSUE THREAD

**Issue by mudspringhiker** [ibm-mas/installer#738]
Current `mas provision-aws` command only supports OCP 4.10.

**Comment by istrate** [comment]
support for higher version will be added via: https://github.com/ibm-mas/cli/pull/700

**Comment by whitfiea** [comment]
Support for OCP 4.13 and 4.14 added in Catalog https://ibm-mas.github.io/cli/catalogs/v8-240326-amd64/ as well as https://github.com/ibm-mas/cli/releases/tag/7.18.0 for provision-aws
