### ISSUE TITLE
Error during roks provision with cli 2.6.1 since plugin is missing (ibmcloud plugin install ks)

### ISSUE THREAD

**Issue by oloher** [ibm-mas/installer#80]
TASK [ibm.mas_devops.ocp_provision : roks : Check if cluster already exists] ******************************************************************************************************************************************
Wednesday 26 October 2022  08:18:01 +0000 (0:00:02.202)       0:00:11.402 *****
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "ibmcloud oc cluster get -c CLUSTERNAME --output json\n", "delta": "0:00:01.459113", "end": "2022-10-26 08:18:03.579984", "failed_when_result": true, "msg": "non-zero return code", "rc": 2, "start": "2022-10-26 08:18:02.120871", "stderr": "FAILED\n'oc' is not a registered command. Check your list of installed plug-ins. See 'ibmcloud help'.", "stderr_lines": ["FAILED", "'oc' is not a registered command. Check your list of installed plug-ins. See 'ibmcloud help'."], "stdout": "", "stdout_lines": []}

NO MORE HOSTS LEFT ****************************************************************************************************************************************************************************************************

[ibmmas/cli:2.6.1]~$ ibmcloud plugin repo-plugins
Getting plug-ins from all repositories...

Repository: IBM Cloud
Status          Name                                            Versions                       Description
Not Installed   container-registry[cr]                          1.0.2, 1.0.1, 1.0.0...         Manage IBM Cloud Container Registry content and configuration.
Not Installed   container-service[kubernetes-service/ks]        1.0.459, 1.0.454, 1.0.452...   Manage IBM Cloud Kubernetes Service clusters
Not Installed   analytics-engine                                1.0.194, 1.0.186, 1.0.181...   Manage Analytics Engine service
Not Installed   cloud-functions[wsk/functions/fn]               1.0.61, 1.0.60, 1.0.59...      Manage Cloud Functions
Not Installed   cloud-internet-services[cis]                    1.14.8, 1.14.5, 1.14.4...      Manage Cloud Internet Service
Not Installed   dbaas-cli[dbaas]                                2.2.0, 2.1.7, 2.1.6...         Manage Hyper Protect DBaaS clusters
Not Installed   cloud-databases[cdb]                            0.12.0, 0.11.0, 0.10.10...     Manage Cloud databases
Not Installed   key-protect[kp]                                 0.6.12, 0.6.11, 0.6.10...      Manage encryption keys on IBM Cloud
Not Installed   doi[doi]                                        0.4.0, 0.3.9, 0.3.8...         Integrate with DevOps Insights service
Not Installed   tke                                             1.3.1, 1.3.0, 1.2.3...         Manage the master key of Cloud HSMs from Hyper Protect Crypto service
Not Installed   cloud-object-storage                            1.6.0, 1.5.0, 1.4.0...         Manage Cloud Object Storage service
Not Installed   event-streams                                   2.3.2, 2.3.1, 2.3.0...         Manage Event Streams service
Not Installed   power-iaas[pi]                                  0.4.3, 0.4.2, 0.4.1...         Manage IBM Cloud Power Virtual Server service
Not Installed   vpc-infrastructure[infrastructure-service/is]   5.4.0, 5.3.0, 5.2.0...         Manage Virtual Private Cloud infrastructure service
Not Installed   schematics[sch]                                 1.12.2, 1.12.1, 1.12.0...      Managing IBM Cloud resources with Terraform
Not Installed   cloud-dns-services[dns]                         0.7.2, 0.7.1, 0.7.0...         Manage IBM Cloud Dns Service
Not Installed   dl-cli[dl]                                      0.5.2, 0.4.11, 0.4.10...       Manage Direct Link
Not Installed   watson                                          0.0.11, 0.0.10, 0.0.9...       Manage Watson services
Not Installed   catalogs-management                             2.2.2, 2.2.1, 2.2.0...         Manage personal catalogs and offerings
Not Installed   tg-cli[tg]                                      0.8.2, 0.7.1, 0.6.1...         Manage Transit Gateway service
Not Installed   observe-service                                 1.0.82, 1.0.61, 1.0.54...      Manage logging and monitoring configurations for IBM Cloud Kubernetes Service clusters
Not Installed   code-engine                                     1.39.6, 1.39.5, 1.39.3...      Manage Code Engine components
Not Installed   hpvs                                            1.4.21, 1.4.19, 1.4.17...      Manage Hyper Protect Virtual Server service
Not Installed   secrets-manager[sm]                             0.1.23, 0.1.22, 0.1.21...      Manage IBM Cloud Secrets Manager secrets and secret groups.
Not Installed   app-configuration[ac]                           1.0.11, 1.0.10, 1.0.9...       Interact with IBM Cloud App Configuration service instance
Not Installed   monitoring                                      0.2.12, 0.2.9, 0.2.8...        Manage IBM Cloud monitoring
Not Installed   logging                                         0.0.8, 0.0.7, 0.0.6...         Manage IBM Cloud logging
Not Installed   cloudant[cl]                                    0.0.6, 0.0.5, 0.0.4...         Manage Cloudant service
Not Installed   hpcs-cert-mgr[hpcs-cert-mgr]                    1.0.0                          Manage the client certificates for IBM Cloud Hyper Protect Crypto Services
Not Installed   atracker[at]                                    0.2.17, 0.2.12, 0.1.13...      Manage IBM Cloud Activity Tracker
Not Installed   analytics-engine-v3[ae-v3]                      2.0.0, 1.0.9, 1.0.5...         Manage serverless Spark instances and run applications
Not Installed   cra[cra]                                        1.0.4, 1.0.3, 1.0.2...         Integrate with Code Risk Analyzer
Not Installed   event-notifications[en/event-notifications]     0.1.2, 0.1.1, 0.1.0...         IBM Cloud Event Notifications.
Not Installed   dvaas[watson-query]                             1.0.2                          Manage data virtualization as a service
Not Installed   hpnet                                           1.0.2, 1.0.1                   Manage Hyper Protect Secure Network
Not Installed   qiskit-runtime[qr]                              0.1.5                          [Beta] Manage Qiskit Runtime
Not Installed   hpcs                                            0.0.1                          Manage Hyper Protect Crypto Services Instances
Not Installed   cbr                                             1.1.0, 1.0.0                   Manage Context Based Restrictions
Not Installed   privileged-access-gateway[pag]                  1.2.2, 1.2.1                   [Experimental] Manage Privilege Access Gateway

Use ibmcloud plugin update PLUGIN_NAME -r REPO_NAME to update a plugin from a repo.
Use ibmcloud plugin update --all -r REPO_NAME to upgrade all available plugins from a repo.

[ibmmas/cli:2.6.1]~$

Solution:
Add this plugin into next build.

ibmcloud plugin install ks

Thanks Olof

**Comment by durera** [comment]
Interesting ... it's meant to be installed ..

```
ibmcloud plugin repo-plugins -r 'IBM Cloud'
ibmcloud plugin install container-service
```

However, unfortunate sideeffect of later running this command:

```
rm -rf /opt/app-root/src/.bluemix
```

is that we delete the plugins, this should really be scoped down to `rm /opt/app-root/src/.bluemix/config.json`
