### ISSUE TITLE
mas-install-restore-morph-failed

### ISSUE THREAD

**Issue by zxue** [ibm-mas/installer#804]
"Mas Install" failed. See the error log. DB2 pod didn't complete, showing "0/1" status.

```
+ echo Completed /db2u/db2u_restore_morph.sh with RC code 1. Total Elapsed Time: 21
+ exit 1
+ echo 'Restore Morph FAILED. Inspect /mnt/blumeta0/db2/.lifecycle/db2u_restore_morph.20240223191847.log for details.'
Restore Morph FAILED. Inspect /mnt/blumeta0/db2/.lifecycle/db2u_restore_morph.20240223191847.log for details.
```

**Comment by QDespeisseTalan** [comment]
I've already met this issue, you can temporary fix the issue by opening the db2 pod's terminal and :
switch to db2inst user :
`su - db2inst1`

Update the memory :
`db2 update dbm cfg using instance_memory 2000000`

Kill the pod and it will restart normally

**Comment by whitfiea** [comment]
@zxue these issues sometimes happen with DB2, and it is not something we can easily control in the MAS install.
