### ISSUE TITLE
`mas update` command fails even if uds, dro, prometheus storageclasses have been exported to env

### ISSUE THREAD

**Issue by mudspringhiker** [ibm-mas/installer#831]
Customer running `mas update` on clusters using storage classes other than odf / ibm storage fails (uds and grafana tasks) even if these have been exported to environment. 

```
TASK [ibm.mas_devops.cluster_monitoring : Assert that Prometheus storage class has been defined] ***
fatal: [localhost]: FAILED! => changed=false 
  assertion: prometheus_storage_class is defined and prometheus_storage_class != ""
  evaluated_to: false
  msg: prometheus_storage_class must be defined
```

```
TASK [ibm.mas_devops.uds : Assert that storage class has been defined] *********
fatal: [localhost]: FAILED! => changed=false 
  assertion: uds_storage_class is defined and uds_storage_class != ""
  evaluated_to: false
  msg: uds_storage_class must be defined
```
even if the following were ran:
```
export PROMETHEUS_STORAGE_CLASS=nfs-storage
export UDS_STORAGE_CLASS=nfs-storage
export DRO_STORAGE_CLASS=nfs-storage
```

Customer then manually runs the `dro` and `cluster_monitoring` roles as workaround however, it would be nice to have the `mas update` command work successfully without having to run the roles as this defeats the purpose of the `mas update` command.

**Comment by lokesh-sreedhara** [comment]
@mudspringhiker. this issue was fixed, can u try the latest version of cli and let me know?
