### ISSUE TITLE
mas mirror-images doesn't support of mirroring DRO

### ISSUE THREAD

**Issue by pohlkamp** [ibm-mas/installer#852]
Hi, 
please extend the cli 7.17.0 to support DRO mirroring. It's listed in help as a valid option but returns when executing that it doesn't exist. 

Update also the GitHub documentation for `mas mirror-images` to provide also the features of DRO. 

https://github.com/ibm-mas/cli/blob/master/docs/commands/mirror-images.md

**Comment by lokesh-sreedhara** [comment]
@pohlkamp DRO is part of certified-operators and its images comes as part of the certified-operators CatalogSource. this comes OOB with OCP, i think u need to enable certified-operators CatalogSource on ur air-gapped cluster, DRO should as part of it. 

![image](https://github.com/ibm-mas/cli/assets/110647904/d4615b3d-4e84-4719-a0b7-6d9c74167c0c)

MAS catalogs does not contain DRO, so we dont have to mirror DRO as part of CLI. The --mirror-dro flag removed as part of https://github.com/ibm-mas/cli/commit/7cbcc8124ce74cadcf8b8733341d5f390f64f8a3

PR: https://github.com/ibm-mas/cli/pull/849
