### ISSUE TITLE
MAS Install CLI does not have option to set DB_SCHEMA, DB_TABLESPACE and DB_INDEXTABLESPACE

### ISSUE THREAD

**Issue by ghost** [ibm-mas/installer#884]
Which is essential, especially for EAM upgrade to Manage scenarios, because those might differ from default/hard-coded values that comes in the ManageWorkspace cr when you run mas install cli.

**Comment by andrercm** [comment]
Will be fixed with this PR: https://github.com/ibm-mas/cli/pull/854
