### ISSUE TITLE
IBM MAS CLI `mas update` command does not have option to set required variables for the update-grafana task (cluster_monitoring role)

### ISSUE THREAD

**Issue by mudspringhiker** [ibm-mas/installer#889]
mas update errors in the update-grafana task due to variables not defined:

- `prometheus_storage_class`
- `prometheus_alertmgr_storage_class`
- `grafana_instance_storage_class`

**Comment by stonepd** [comment]
[ansible-devops v19.1.0](https://github.com/ibm-mas/ansible-devops/releases/tag/19.1.0) has a fix to get the storage class configuration from the previous V4 operator settings.
