### ISSUE TITLE
In airgap installation, how to retrieve image digest for quay.io/ibmmas/cli:2.6.1?

### ISSUE THREAD

**Issue by liupinyi** [ibm-mas/installer#91]
How to retrieve image digest for quay.io/ibmmas/cli:2.6.1 in mascli?

![image](https://user-images.githubusercontent.com/21214618/198183458-1d4f9866-12c1-429c-94e7-3d49fa0ecb07.png)

**Comment by liupinyi** [comment]
how to fix this issue?

**Comment by liupinyi** [comment]
If my bastion machine can connect to Internet, then it can retrieve the SHA256.

**Comment by durera** [comment]
Working on a fix for this ... we will detect whether the host can reach quay.io .. if it cannot it will allow the user to manually enter the digest to be used :+1:

**Comment by liupinyi** [comment]
@durera Thank you David.
