### ISSUE TITLE
Cannot skip grafana installation using cli

### ISSUE THREAD

**Issue by gisunkim** [ibm-mas/installer#946]
Airgap installation failed with grafana-operator and was guided to skip grafana installation using : export CLUSTER_MONITORING_INCLUDE_GRAFANA=False 

export variable doesn't work due to 2 issue:
- Looks like MAS CLI does not provide the logic to skip grafana install, according the current design (if the packagemanifest can be found it will always install) https://github.com/ibm-mas/cli/blob/master/image/cli/mascli/functions/install
- Once installation failed and when re-running pre-check keep look for grafana status so cannot proceed even forcing cli to skip grafana(ibm/mas_devops/roles/ocp_verify). Had to use --skip-pre-check to skip full pre-check which customer doesn't like

customer version : cli 8.1.0
tested version : cli 8.2.2

**Comment by andrercm** [comment]
Triage with @sanjayprab a fix for that is planned to come soon.

**Comment by durera** [comment]
Contained in https://github.com/ibm-mas/cli/pull/827
