### ISSUE TITLE
DB2 sizing is not getting set on DB2uCluster instance using CLI

### ISSUE THREAD

**Issue by sbudhira** [ibm-mas/installer#97]
The DB2 sizing is not getting set on DB2uCluster instance using CLI

export DB2_META_STORAGE_SIZE=10Gi 
export DB2_BACKUP_STORAGE_SIZE=10Gi
export DB2_LOGS_STORAGE_SIZE=10Gi
export DB2_TEMP_STORAGE_SIZE=10Gi
export DB2_DATA_STORAGE_SIZE=20Gi

DB2U cluster instance shows the default values set at the playbook.

storage:
    - name: meta
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: odf-lvm-vg1
      type: create
    - name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: odf-lvm-vg1
      type: template
    - name: backup
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: odf-lvm-vg1
      type: create
    - name: activelogs
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: odf-lvm-vg1
      type: template
    - name: tempts
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: odf-lvm-vg1
      type: template
  version: 11.5.7.0-cn4
  
  
  Dev Branch: db2test

**Comment by hughjfchen** [comment]
I believe the memory sizing also has the same problem. I remembered I'd been hit by this issue months ago.
