### ISSUE TITLE
`mas uninstall` fails at `uninstall-uds`

### ISSUE THREAD

**Issue by mudspringhiker** [ibm-mas/installer#989]
`mas uninstall` gives an error in the delete the GenerateKey, uds role (uninstall) 

(probably only happens for recently installed instances that use DRO).

```
TASK [ibm.mas_devops.uds : uninstall : Delete the GenerateKey] *****************
fatal: [localhost]: FAILED! => changed=false 
  msg: Failed to find exact match for uds.ibm.com/v1.GenerateKey by [kind, name, singularName, shortNames]
```

- reproduced from a customer issue

**Comment by durera** [comment]
This has been fixed here: https://github.com/ibm-mas/ansible-devops/pull/1354

The fix is available in the latest versions of the MAS CLI
