### ISSUE TITLE
Mirror image failed for some MAS component and version

### ISSUE THREAD

**Issue by nutpapon-tripledotconsult** [ibm-mas/installer#993]
Hi,

I am writing regarding the mas-cli mirror image.
I want to create a local registry for MAS offline installation for 2 environments. 
The first environment requires MAS 8.10 with Mange, Iot, and Monitor.
The second environment requires MAS 8.11 with Mange, Iot, Monitor, and Predict.
The mirror process had returned with errors

The following is the code I used to create a local registry on the RHEL bastion machine.
podman run --name registry_mas810 -p 5010:5000 -v /opt/registry/registry_mas810:/var/lib/registry:z -v /opt/registry/auth:/auth:z -e "REGISTRY_AUTH=htpasswd" -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd -v /opt/registry/certs:/certs:z -e "REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt" -e "REGISTRY_HTTP_TLS_KEY=/certs/domain.key" -e REGISTRY_COMPATIBILITY_SCHEMA1_ENABLED=true -d docker.io/library/registry:latest

The following is the status from each log file, please see in the attachment mas_mirror_log.zip. 
v8-231228-amd64 
mirror-20240524-095835-core.log  ok=27 failed=0 
mirror-20240524-095835-manage.log    ok=26 failed=1 
mirror-20240524-095835-monitor.log ok=50 failed=0
mirror-20240524-095835-iot.log  ok=45 failed=1
mirror-20240524-095835-dependencies.log  ok=41 failed=1

v8-231228-amd64
mirror-20240523-082617-core.log         ok=27 failed=0 
mirror-20240523-082617-manage.log   ok=27 failed=0 
Mirror-20240523-082617-monitor.log   ok=50 failed=0
mirror-20240523-082617-dependencies.log  failed
Mirror-20240523-082617-optimizer.log ok=27 failed=0
mirror-20240523-082617-iot.log      ok=45 failed=1     
Mirror-20240523-082617-predict.log ok=10 failed=1

Most of the errors are about 'error: unable to copy layer sha256:xxx stream error: stream ID xx; INTERNAL_ERROR; received from peer'.
[mas_mirror_log.zip](https://github.com/ibm-mas/cli/files/15452343/mas_mirror_log.zip)

**Comment by durera** [comment]
There's a couple of different errors in here:

```
TASK [ibm.mas_devops.mirror_case_prepare : ibm-mas-predict : Get the CASE bundle] ***
fatal: [localhost]: FAILED! => changed=true 
  cmd: 'oc ibm-pak get ibm-mas-predict --version 8.9.2   '
  delta: '0:00:17.595394'
  end: '2024-05-23 13:32:23.783265'
  msg: non-zero return code
  rc: 1
  start: '2024-05-23 13:32:06.187871'
  stderr: 'Error: Get "https://github.com/IBM/cloud-pak/raw/master/repo/case/ibm-mas-predict/8.9.2/ibm-mas-predict-8.9.2.tgz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)'
  stderr_lines: <omitted>
  stdout: Downloading and extracting the CASE ...
  stdout_lines: <omitted>
```

and 

```
    - 'info: Planning completed in 3.39s'
    - 'uploading: bastion.demo.tdc:5000/kubebuilder/kube-rbac-proxy sha256:0d7d70899875b098ace120b574f57b39e91415ceaf9b348d6abe168537509f5a 642.3KiB'
    - 'uploading: bastion.demo.tdc:5000/kubebuilder/kube-rbac-proxy sha256:ccc5b96d7521398cba9a85cd625aacd45453456365ede70e0e2e9362194408e7 17.67MiB'
    - 'uploading: bastion.demo.tdc:5000/kubebuilder/kube-rbac-proxy sha256:f3347552f9faf9335baff9cb0def4c2251ffd73c5c338c26a3dc071a4f4904e7 16.42MiB'
    - 'uploading: bastion.demo.tdc:5000/kubebuilder/kube-rbac-proxy sha256:c500cd5e4a349c5cceb9fae739a12bae0bc359e75e25110eb6c55062de20a5d6 17.52MiB'
    - 'uploading: bastion.demo.tdc:5000/kubebuilder/kube-rbac-proxy sha256:0180d46323d9cdf9965aaff6c474e81edf63f3642684f7ad353f50972ad11681 16.09MiB'
    - 'uploading: bastion.demo.tdc:5000/amlen/operator sha256:d661b916c2583bd479813d8f14887d7cefe963df2a689d93f60304e2e11c759e 3.629MiB'
    - 'uploading: bastion.demo.tdc:5000/amlen/operator sha256:0cf957ba1c931384203cb8184442f48527d06ecda2efd8a8bbb546cce4acbe5a 108.1MiB'
    - 'uploading: bastion.demo.tdc:5000/amlen/operator sha256:19b323993c37b6fc3a8a38c38cb6581b3fa4d4bf789b83ac00fb760d14ab8512 77.73MiB'
    - 'uploading: bastion.demo.tdc:5000/amlen/operator sha256:f89303c94afb3ac8a1620e71c1cdfb2af0a303f2ea744cbdd0a3dfcef8957ce1 17.16KiB'
    - 'uploading: bastion.demo.tdc:5000/amlen/operator sha256:fb2979a3ecdb5f2213b95b3801fbccd8c664049d924f26485b28ece9e7add34f 23.35MiB'
    - 'uploading: bastion.demo.tdc:5000/amlen/operator sha256:e67584884560b5306b5d7f4906a0b6ed166bfd110cfae255784105347b71c0e6 3.613MiB'
    - 'error: unable to copy layer sha256:19b323993c37b6fc3a8a38c38cb6581b3fa4d4bf789b83ac00fb760d14ab8512 to bastion.demo.tdc:5000/amlen/operator: Patch "https://bastion.demo.tdc:5000/v2/amlen/operator/blobs/uploads/ae9c9d73-f7b4-4db2-9f57-fea40f58640d?_state=pZ8q8G_YdBUISKfDjNXCYXgNfakzyEdmSN2lJuDPZed7Ik5hbWUiOiJhbWxlbi9vcGVyYXRvciIsIlVVSUQiOiJhZTljOWQ3My1mN2I0LTRkYjItOWY1Ny1mZWE0MGY1ODY0MGQiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjQtMDUtMjNUMTA6MTM6NDAuMDE4NjE3NTE0WiJ9": stream error: stream ID 25; INTERNAL_ERROR; received from peer'
    - 'info: Mirroring completed in 6m1.41s (600.7kB/s)'
    - 'error: one or more errors occurred while uploading images'
```

Both indicate a network problem.  I would expect that re-running the commands is sufficient to complete the mirroring, the existing content that was already mirrored won't be downloaded/uploaded again, so the re-run should be short.
